fix: Make `sed` command cross-platform.
"bin/init::set_up_config_files" error on MacOS due to `seb` implementation on BSD

Error: sed: 1: "...": extra characters at the end of n command

Reference: https://stackoverflow.com/questions/16745988/sed-command-with-i-option-in-place-editing-works-fine-on-ubuntu-but-not-mac